site_description: "Nativescript Vue Web"
google_analytics: "dev"
root_domain: nativescript-vue-web.org
vue_version: 2.5.16

special_sponsors:
  - url: https://nuweb.com
    img: nuweb.png
    name: nuweb

# platinum_sponsors:
    #  - url: http://www.nurd.net/
    #img: nurd-logo.png
    #name: nurd
