site_description: "Nativescript Vue Web"
google_analytics: "dev"
root_domain: nativescript-vue-web.org
vue_version: 2.5.16

special_sponsors:
  - url: https://nuweb.com
    img: nuweb.png
    name: nuweb

platinum_sponsors:
  - url: https://www.nativescript.org/vue?utm_source=vue-js-org&utm_medium=website&utm_campaign=nativescript-awareness
    img: nativescript.png
    name: nativescript
