# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: Nativescript-Vue-Web
subtitle:
description: "One Code, Many Platforms"
author: NuWeb
email:
language: en

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://nativescript-vue-web.org/
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: vue
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Offline
## Config passed to sw-precache
## https://github.com/JLHwung/hexo-offline
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,jpeg,gif,svg,eot,ttf,woff,woff2,json,xml}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.googleapis.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.gstatic.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: maxcdn.bootstrapcdn.com

# Deployment
deploy:
  type: git
  repository: git@github.com:Nativescript-Vue-Web/nativescript-vue-web.org.git

feed:
  type: atom
  path: atom.xml
  limit: 20

alias:
  api/index.html: v1/api/index.html
  guide/class-and-style.html: v1/guide/class-and-style.html
  guide/comparison.html: v1/guide/comparison.html
  guide/components.html: v1/guide/components.html
  guide/computed.html: v1/guide/computed.html
  guide/conditional.html: v1/guide/conditional.html
  guide/custom-directive.html: v1/guide/custom-directive.html
  guide/deployment.html: v1/guide/deployment.html
  guide/events.html: v1/guide/events.html
  guide/forms.html: v1/guide/forms.html
  guide/index.html: v1/guide/index.html
  guide/installation.html: v1/guide/installation.html
  guide/instance.html: v1/guide/instance.html
  guide/join.html: v1/guide/join.html
  guide/list.html: v1/guide/list.html
  guide/migration-vue-router.html: v1/guide/migration-vue-router.html
  guide/migration-vuex.html: v1/guide/migration-vuex.html
  guide/migration.html: v1/guide/migration.html
  guide/mixins.html: v1/guide/mixins.html
  guide/plugins.html: v1/guide/plugins.html
  guide/reactivity.html: v1/guide/reactivity.html
  guide/render-function.html: v1/guide/render-function.html
  guide/routing.html: v1/guide/routing.html
  guide/single-file-components.html: v1/guide/single-file-components.html
  guide/ssr.html: v1/guide/ssr.html
  guide/state-management.html: v1/guide/state-management.html
  guide/syntax.html: v1/guide/syntax.html
  guide/transitioning-state.html: v1/guide/transitioning-state.html
  guide/transitions.html: v1/guide/transitions.html
  guide/unit-testing.html: v1/guide/unit-testing.html
  examples/commits.html: v1/examples/commits.html
  examples/elastic-header.html: v1/examples/elastic-header.html
  examples/firebase.html: v1/examples/firebase.html
  examples/grid-component.html: v1/examples/grid-component.html
  examples/hackernews.html: v1/examples/hackernews.html
  examples/index.html: v1/examples/index.html
  examples/modal.html: v1/examples/modal.html
  examples/select2.html: v1/examples/select2.html
  examples/svg.html: v1/examples/svg.html
  examples/todomvc.html: v1/examples/todomvc.html
  examples/tree-view.html: v1/examples/tree-view.html
